#!/bin/sh

if [ $# -ne 2 ]; then
    echo "usage: ${0} (commit) (linux dir)"
    exit 1
fi

CUR=`pwd`
cd ${2}

ver=`git describe ${1}^ | cut -d - -f1`
if [ `echo ${ver} | grep -c "v2\.6\.[12][0-9]"` -eq 0 ]; then
    MAKE="make"
else
    MAKE="../make-3.81/make"
fi

files=(`git diff --name-only ${1} ${1}^ | grep \.c$ | sed -e 's/\.c$/\.o/g'`)

git checkout ${1}^
patch -p 1 < ${CUR}/${ver}

${MAKE} allyesconfig

./scan-build2 \
-load-plugin ~/llvm/Release/lib/IRQChecker.so \
-enable-checker linux.IRQChecker \
${MAKE} CC=/usr/local/bin/clang HOSTCC=/usr/local/bin/clang \
${files[@]}

git reset master --hard
cd ${CUR}

