#!/bin/sh -u

function scanbuild2() {
  local OPTIONS="-disable-checker alpha.core.BoolAssignment \
  -disable-checker alpha.core.CallAndMessageUnInitRefArg \
  -disable-checker alpha.core.CastSize \
  -disable-checker alpha.core.CastToStruct \
  -disable-checker alpha.core.FixedAddr \
  -disable-checker alpha.core.IdenticalExpr \
  -disable-checker alpha.core.PointerArithm \
  -disable-checker alpha.core.PointerSub \
  -disable-checker alpha.core.SizeofPtr \
  -disable-checker alpha.cplusplus.NewDeleteLeaks \
  -disable-checker alpha.cplusplus.VirtualCall \
  -disable-checker alpha.deadcode.UnreachableCode \
  -disable-checker alpha.osx.cocoa.Dealloc \
  -disable-checker alpha.osx.cocoa.DirectIvarAssignment \
  -disable-checker alpha.osx.cocoa.DirectIvarAssignmentForAnnotatedFunctions \
  -disable-checker alpha.osx.cocoa.InstanceVariableInvalidation \
  -disable-checker alpha.osx.cocoa.MissingInvalidationMethod \
  -disable-checker alpha.security.ArrayBound \
  -disable-checker alpha.security.ArrayBoundV2 \
  -disable-checker alpha.security.MallocOverflow \
  -disable-checker alpha.security.ReturnPtrRange \
  -disable-checker alpha.security.taint.TaintPropagation \
  -disable-checker alpha.unix.Chroot \
  -disable-checker alpha.unix.MallocWithAnnotations \
  -disable-checker alpha.unix.PthreadLock \
  -disable-checker alpha.unix.SimpleStream \
  -disable-checker alpha.unix.Stream \
  -disable-checker alpha.unix.cstring.BufferOverlap \
  -disable-checker alpha.unix.cstring.NotNullTerminated \
  -disable-checker alpha.unix.cstring.OutOfBounds \
  -disable-checker core.CallAndMessage \
  -disable-checker core.DivideZero \
  -disable-checker core.DynamicTypePropagation \
  -disable-checker core.NonNullParamChecker \
  -disable-checker core.NullDereference \
  -disable-checker core.StackAddressEscape \
  -disable-checker core.UndefinedBinaryOperatorResult \
  -disable-checker core.VLASize \
  -disable-checker core.builtin.BuiltinFunctions \
  -disable-checker core.builtin.NoReturnFunctions \
  -disable-checker core.uninitialized.ArraySubscript \
  -disable-checker core.uninitialized.Assign \
  -disable-checker core.uninitialized.Branch \
  -disable-checker core.uninitialized.CapturedBlockVariable \
  -disable-checker core.uninitialized.UndefReturn \
  -disable-checker cplusplus.NewDelete \
  -disable-checker deadcode.DeadStores \
  -disable-checker debug.ConfigDumper \
  -disable-checker debug.DumpCFG \
  -disable-checker debug.DumpCallGraph \
  -disable-checker debug.DumpCalls \
  -disable-checker debug.DumpDominators \
  -disable-checker debug.DumpLiveVars \
  -disable-checker debug.DumpTraversal \
  -disable-checker debug.ExprInspection \
  -disable-checker debug.Stats \
  -disable-checker debug.TaintTest \
  -disable-checker debug.ViewCFG \
  -disable-checker debug.ViewCallGraph \
  -disable-checker debug.ViewExplodedGraph \
  -disable-checker llvm.Conventions \
  -disable-checker osx.API \
  -disable-checker osx.SecKeychainAPI \
  -disable-checker osx.cocoa.AtSync \
  -disable-checker osx.cocoa.ClassRelease \
  -disable-checker osx.cocoa.IncompatibleMethodTypes \
  -disable-checker osx.cocoa.Loops \
  -disable-checker osx.cocoa.MissingSuperCall \
  -disable-checker osx.cocoa.NSAutoreleasePool \
  -disable-checker osx.cocoa.NSError \
  -disable-checker osx.cocoa.NilArg \
  -disable-checker osx.cocoa.NonNilReturnValue \
  -disable-checker osx.cocoa.RetainCount \
  -disable-checker osx.cocoa.SelfInit \
  -disable-checker osx.cocoa.UnusedIvars \
  -disable-checker osx.cocoa.VariadicMethodTypes \
  -disable-checker osx.coreFoundation.CFError \
  -disable-checker osx.coreFoundation.CFNumber \
  -disable-checker osx.coreFoundation.CFRetainRelease \
  -disable-checker osx.coreFoundation.containers.OutOfBounds \
  -disable-checker osx.coreFoundation.containers.PointerSizedValues \
  -disable-checker security.FloatLoopCounter \
  -disable-checker security.insecureAPI.UncheckedReturn \
  -disable-checker security.insecureAPI.getpw \
  -disable-checker security.insecureAPI.gets \
  -disable-checker security.insecureAPI.mkstemp \
  -disable-checker security.insecureAPI.mktemp \
  -disable-checker security.insecureAPI.rand \
  -disable-checker security.insecureAPI.strcpy \
  -disable-checker security.insecureAPI.vfork \
  -disable-checker unix.API \
  -disable-checker unix.Malloc \
  -disable-checker unix.MallocSizeof \
  -disable-checker unix.MismatchedDeallocator \
  -disable-checker unix.cstring.BadSizeArg \
  -disable-checker unix.cstring.NullArg"

  local nextEnableChecker=0
  local args=()
  local enableCheckers=()
  local arg=""
  for arg in ${@}; do
    if [ ${nextEnableChecker} -eq 1 ]; then
      enableCheckers+=(${arg})
      nextEnableChecker=0
    elif [ "${arg}" = "-enable-checker" ]; then
      nextEnableChecker=1
    fi
    args+=(${arg})
  done

  if [ ${#enableCheckers[*]} -ne 0 ]; then
    local enableChecker=""
    for enableChecker in ${enableCheckers[@]}; do
      OPTIONS=`echo "${OPTIONS}" | sed -e "s/-disable-checker ${enableChecker}/-enable-checker ${enableChecker}/g"`
    done
  fi
  scan-build -load-plugin ~/llvm/Release/lib/BugChecker.so ${OPTIONS} \
             --use-analyzer=/usr/local/bin/clang --use-cc=/usr/local/bin/clang \
             -analyze-headers -maxloop 10 ${args[@]} 
}

if [ $# -eq 0 ]; then
  scan-build
  exit 1
fi

scanbuild2 ${@}
